// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateArticle(arg1:main.Article):Promise<void>;

export function GetArticles(arg1:string,arg2:string,arg3:string):Promise<Array<main.Article>>;

export function Sale(arg1:Array<main.Article>):Promise<void>;
